{
 "title": "Internet centralization",
 "time": { "from": "2015-04-15T21:44:31.000Z", "to": "2021-04-15T07:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "included_markets",
    "query": "select market from provider_marketshare where market in ('web-hosting', 'ssl-certificate', 'proxy',  'dns-server','data-centers', 'server-location', 'top-level-domain');"
   },
   {
    "name": "EU_alpha2s",
    "query": "'AT','BE','BG','CY','CZ','DK','EE','FI','FR','DE','GR','HU','IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gini coefficients across markets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval,previous),\n  market AS metric,\n  avg(gini) AS \"gini\"\nFROM pop_weighted_gini\nWHERE\n  $__timeFilter(\"time\") AND\n  market IN ($included_markets)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Changes in mean marketshare",
   "type": "table",
   "gridPos": { "h": 9, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",$__interval),\n  jurisdiction_alpha2 AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  market IN ($included_markets) AND\n  jurisdiction_alpha2 IS NOT null\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "EU+GB+NO+CH marketshare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  market AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  market IN ($included_markets) AND\n  jurisdiction_alpha2 IN (${EU_alpha2s:raw})\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "US marketshare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  market AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  jurisdiction_alpha2 = 'US' AND\n  market IN ($included_markets)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "CN marketshare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  market AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  jurisdiction_alpha2 = 'CN' AND\n  market IN ($included_markets)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "RU marketshare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  market AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  jurisdiction_alpha2 = 'RU' AND\n  market IN ($included_markets)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Rest of World marketshare",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1h),\n  market AS metric,\n  sum(marketshare) AS \"marketshare\"\nFROM provider_marketshare\nWHERE\n  $__timeFilter(\"time\") AND\n  jurisdiction_alpha2 NOT IN ('US', 'RU','CN', 'CH', 'GB', 'NO',${EU_alpha2s:raw}) AND\n  market IN ($included_markets)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}